pipeline {
    agent {
        label 'windows'  // Use Windows agent
    }
    
    parameters {
        choice(
            name: 'TEST_ENVIRONMENT',
            choices: ['dev', 'staging', 'uat', 'prod'],
            description: 'Target test environment'
        )
        string(
            name: 'TEST_SUITE',
            defaultValue: 'FrontPage.DummyAPI',
            description: 'FitNesse test suite to run (e.g., FrontPage.DummyAPI, FrontPage.Sanity, FrontPage.Smoke)'
        )
        booleanParam(
            name: 'SEND_EMAIL',
            defaultValue: true,
            description: 'Send email notification with test results'
        )
        booleanParam(
            name: 'FAIL_ON_ERROR',
            defaultValue: true,
            description: 'Fail the build if tests fail'
        )
    }
    
    environment {
        PYTHONPATH = "${WORKSPACE}"
    }
    
    stages {
        stage('Initialize & Diagnostic') {
            steps {
                bat 'echo Working Directory: %CD%'
                bat 'python --version || echo "Python not found"'
                bat 'java -version || echo "Java not found"'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                bat '.venv\\Scripts\\python -m pip install --upgrade pip || pip install --upgrade pip'
                bat '.venv\\Scripts\\pip install -r requirements.txt || pip install -r requirements.txt'
            }
        }
        
        stage('Configure Environment') {
            steps {
                script {
                    // Set up base URLs based on environment selection
                    def baseUrl = "https://dev-api.icici.com"
                    if (params.TEST_ENVIRONMENT == 'staging') {
                        baseUrl = "https://staging-api.icici.com"
                    } else if (params.TEST_ENVIRONMENT == 'uat') {
                        baseUrl = "https://uat-api.icici.com"
                    } else if (params.TEST_ENVIRONMENT == 'prod') {
                        baseUrl = "https://api.icici.com"
                    }
                    
                    // Create local .env file for execution
                    def envContent = """# Generated by Jenkins Pipeline
ENVIRONMENT=${params.TEST_ENVIRONMENT}
DEV_BASE_URL=https://dev-api.icici.com
STAGING_BASE_URL=https://staging-api.icici.com
UAT_BASE_URL=https://uat-api.icici.com
PROD_BASE_URL=https://api.icici.com
API_ADMIN_USER=admin
API_ADMIN_PASS=admin123
TOKEN_ENCRYPTION_KEY=uz827x4e_RwsYDfghjklmnopqrstudvwxyz12345678=
MOCK_SERVER_PORT=8089
"""
                    writeFile file: '.env', text: envContent, encoding: 'UTF-8'
                    echo "Environment configured for ${params.TEST_ENVIRONMENT} with URL ${baseUrl}"
                }
            }
        }
        
        stage('Run pytest Unit Tests') {
            steps {
                bat '.venv\\Scripts\\pytest tests/unit/ --cov=core --cov-report=xml || pytest tests/unit/ --cov=core --cov-report=xml'
            }
        }
        
        stage('Run FitNesse Test Suite') {
            steps {
                script {
                    // Clean previous ports
                    bat 'for /f "tokens=5" %a in (\'netstat -aon ^| findstr :8080\') do taskkill /f /pid %a >nul 2>&1 || exit 0'
                    bat 'for /f "tokens=5" %a in (\'netstat -aon ^| findstr :8085\') do taskkill /f /pid %a >nul 2>&1 || exit 0'
                    
                    // Launch FitNesse in background using Windows start command
                    echo "Starting FitNesse Server..."
                    bat 'start /b java -cp fitnesse-standalone.jar fitnesseMain.FitNesseMain -p 8080 -e 0 > fitnesse_output.log 2> fitnesse_errors.log'
                    
                    // Wait for server to start and verify
                    echo "Waiting for FitNesse Server response..."
                    sleep time: 15, unit: 'SECONDS'
                    
                    // Execute tests via Python integration check or powershell URL request
                    def exitCode = 0
                    try {
                        echo "Executing FitNesse Suite: ${params.TEST_SUITE}"
                        // Trigger test execution page run
                        powershell """
                            \$headers = @{ 'Accept' = 'application/json' }
                            \$url = 'http://localhost:8080/${params.TEST_SUITE}?suite&format=json'
                            try {
                                \$res = Invoke-WebRequest -Uri \$url -Headers \$headers -UseBasicParsing -TimeoutSec 600
                                \$res.Content | Out-File -FilePath 'fitnesse_response.json' -Encoding utf8
                                Write-Host "Test Run completed. Status: \$(\$res.StatusCode)"
                            } catch {
                                Write-Error "FitNesse run failed: \$_"
                                exit 1
                            }
                        """
                    } catch (Exception e) {
                        echo "Error executing FitNesse suite: ${e.message}"
                        exitCode = 1
                    }
                    
                    // Clean up FitNesse process
                    echo "Stopping FitNesse Server..."
                    bat 'for /f "tokens=5" %a in (\'netstat -aon ^| findstr :8080\') do taskkill /f /pid %a >nul 2>&1 || exit 0'
                    bat 'for /f "tokens=5" %a in (\'netstat -aon ^| findstr :8085\') do taskkill /f /pid %a >nul 2>&1 || exit 0'
                    
                    if (exitCode != 0 && params.FAIL_ON_ERROR) {
                        error "FitNesse Test Suite failed to execute cleanly."
                    }
                }
            }
        }
    }
    
    post {
        always {
            // Archive test output, logs and html reports
            archiveArtifacts artifacts: 'logs/*.log, FitNesseRoot/files/report.html, *.log, *.json', allowEmptyArchive: true
            
            script {
                if (params.SEND_EMAIL) {
                    echo "Sending email notification..."
                    // Example mail trigger (requires Jenkins mail plugin configured)
                    // mail to: 'qa-team@icici.com',
                    //      subject: "Build ${BUILD_NUMBER}: FitNesse Test Suite Complete - Status: ${currentBuild.result}",
                    //      body: "Test execution finished on ${params.TEST_ENVIRONMENT}. Check results at ${BUILD_URL}artifacts"
                }
            }
        }
    }
}
